options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'test-function'
  - '--runtime=nodejs18'
  - '--trigger-http'
  - '--entry-point=helloWorld'
  - '--source=.'
  - '--region=europe-west1'
  - '--allow-unauthenticated'