steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'addressLookup'
  - '--runtime=nodejs18'
  - '--trigger-http'
  - '--entry-point=addressLookup'
  - '--region=europe-west1'
  - '--allow-unauthenticated'