options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'address-lookup-new'
  - '--gen2=false'  # Specificerar 1st gen
  - '--runtime=nodejs18'
  - '--trigger-http'
  - '--entry-point=addressLookup'
  - '--source=.'
  - '--region=europe-west1'
  - '--allow-unauthenticated'