options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - 'ls -la && echo "Current directory content" && cat package.json && cat test.js'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'test-function'
  - '--runtime=nodejs18'
  - '--trigger-http'
  - '--entry-point=helloWorld'
  - '--source=.'
  - '--region=europe-west1'
  - '--allow-unauthenticated'