name: Deploy to Cloud Functions

on:
  push:
    branches:
      - master  # Eller 'main' beroende på din branch-struktur

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Setup GCloud Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    - name: Deploy Function
      run: |
        gcloud functions deploy address-lookup-new \
          --gen2=false \
          --runtime=nodejs20 \
          --region=europe-west1 \
          --source=. \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point=addressLookup \
          --project=${{ secrets.GCP_PROJECT_ID }}