- name: Deploy Function
  run: |
    gcloud functions deploy address-lookup-new \
    --no-gen2 \
      --runtime=nodejs18 \
      --region=europe-west1 \
      --source=. \
      --trigger-http \
      --allow-unauthenticated \
      --entry-point=addressLookup \
      --project=${{ secrets.GCP_PROJECT_ID }}
